In [1]:
#Import needed library.
import pandas as pd

In [2]:
df = pd.read_csv('ARCAUF_DATA.csv',delimiter=',',header='infer')
df

,DATE,TRUCK,DRIVER,START_DATE,START_PLACE,END_DATE,END_PLACE,DRIVING_TIME,STOP_TIME,CAN_DISTANCE,GPS_DISTANCE,USED_FUEL,MEAN_USED-FUEL,MEAN_SPEAD,MAX_SPEED,START_MILEAGE,END_MILEAGE
0,2020-06-17,SMI 02585,NaN,brak,brak,brak,brak,00:00:00,00:01:00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00
1,2020-06-17,ST 8022R,NaN,brak,brak,brak,brak,00:00:00,00:01:00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00
2,2020-06-17,PO 3FX35,NaN,brak,brak,brak,brak,00:00:00,00:01:00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00
3,2020-06-17,ST 5338N,NaN,brak,brak,brak,brak,00:00:00,00:01:00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00
4,2020-06-17,SMI 03266,NaN,brak,brak,brak,brak,00:00:00,00:01:00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN